### ISSUE TITLE
Expose NotifierOptionsToken injection token

### ISSUE THREAD

**Issue by mprey** [dominique-mueller/angular-notifier#100]
Hello,

I am creating a wrapper for your library, and I would like the ability to override the injection token `NotifierOptionsToken` so I can provide your module options on the fly.

It would be as simple as adding
`export { NotifierOptionsToken } from './src/notifier.module';`
to the `index.ts` file. Thank you!

**Comment by dominique-mueller** [comment]
That's a good idea, I'm happy to accept a PR :)

**Comment by dominique-mueller** [comment]
Fixed implicitely by #134, `angular-notifier` should now export everything it comes with.
