### ISSUE TITLE
Can we add images or icons before the text message

### ISSUE THREAD

**Issue by shaukath** [dominique-mueller/angular-notifier#107]
Hi There,

Its really good and helpful. I just want to confirm **Can we add images or icons before the text message?**
And need to change the **_background colors_** as well, 

If it is possible help me regarding this.

**Comment by dominique-mueller** [comment]
- Changing background colors can easily be achieved using SASS / CSS. See the themes section for further details: https://github.com/dominique-mueller/angular-notifier#theme
- Adding custom content to notifications, such as images or icons, is possible using `ng-template`s. Take a look at the docs: https://github.com/dominique-mueller/angular-notifier#custom-templates

**Comment by shaukath** [comment]
Thank you for your reply. Its helped me to add the icons and colors

**Comment by sapxiaojun0226** [comment]
> * Changing background colors can easily be achieved using SASS / CSS. See the themes section for further details: https://github.com/dominique-mueller/angular-notifier#theme
> * Adding custom content to notifications, such as images or icons, is possible using `ng-template`s. Take a look at the docs: https://github.com/dominique-mueller/angular-notifier#custom-templates

Hi, I have write a customize css, and define 
`.notifier__notification--customize {
    background-color: blueviolet; 
    color: aliceblue;
    border-radius: 3px;
	box-shadow: 0 1px 3px rgba(0, 0, 0, .2);
    cursor: default;
    padding-left: 2px
}`

then use `customize` as my theme in my configuration. 
but it didn't work at all.
any wrong with my implement?

BR,
June
