### ISSUE TITLE
Change color of success notification to green

### ISSUE THREAD

**Issue by sarahsga** [dominique-mueller/angular-notifier#11]
"Success" feedback is usually shown in green. The success notification container should be green instead of the current pale yellow

**Comment by dominique-mueller** [comment]
Oh my, there are my red-green visual impairments showing off - any ideas for a better success color? Maybe even better colors for the other notification types?

Happy to get some ideas!

**Comment by dominique-mueller** [comment]
Released version **1.0.6** with the color changes. Thanks again for contributung!
