### ISSUE TITLE
Add support for angular 7

### ISSUE THREAD

**Issue by FeiVincent** [dominique-mueller/angular-notifier#114]

**Comment by JoshuaNitschke** [comment]
@witek1902 

FYI I am using this in an Angular 7 app (that started out as a 6) and it seems to work fine, although I do get an NPM install warning.

npm WARN angular-notifier@4.1.1 requires a peer of @angular/common@>= 6.0.0 < 7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-notifier@4.1.1 requires a peer of @angular/core@>= 6.0.0 < 7.0.0 but none is installed. You must install peer dependencies yourself.

**Comment by danner26** [comment]
If we could just get the deps updated it should work fine I believe.

**Comment by vajnorcan** [comment]
it doesn't work for me. any updates? (in the meantime I'll try to go through the source and see what the issue is)

**Comment by WojciechSlyp** [comment]
Same here.

**Comment by elimin8r** [comment]
well i guess we should change this to "support for angular 8" lol

**Comment by danner26** [comment]
Agreed

**Comment by dominique-mueller** [comment]
Fixed by #134, released as `5.0.0`. Also note that #139 adds support for Angular 8, released as `6.0.0`. Enjoy!
