### ISSUE TITLE
how to make NotifierService work on iphone?

### ISSUE THREAD

**Issue by aisam91** [dominique-mueller/angular-notifier#122]
In my angular site, I used NotifierService from angular-notifier to show notifications. it worked fine on all devices but it didnt work on iphone(the notification is not shown). After tracing on Mac I found this error on console : this.element.animate is not a function. Any suggestions?

**Comment by fedealu** [comment]
Im having the same problem. Its neither working on Safari or Chrome mobile! :(

**Comment by dominique-mueller** [comment]
Duplicate of #116 and #133. The `element.animate()` function is part of the Web Animations API which older browsers might not support. Look into the [compatibility section of the README](https://github.com/dominique-mueller/angular-notifier#browser-support--polyfills), it states that adding the [Web Animation API polyfill](https://github.com/web-animations/web-animations-js) should solve your issue.

Feel free to open up another GitHub issue if the problem continues to exist.
