### ISSUE TITLE
Add NotifierContainerComponent to the index for testing

### ISSUE THREAD

**Issue by eitanfar** [dominique-mueller/angular-notifier#123]
First of all, thanks for a great package !

I would like the NotifierContainerComponent to be added to the index, since for testing purposes, I'm using MockComponent (from ng-mocks), which requires the component in order to mock it.
The fact that I cannot import the component, means that I have to create an empty component of the same name, just to be able to mock it.

Thanks in advance,
Eitan

**Comment by dominique-mueller** [comment]
Fixed implicitely by #134, `angular-notifier` should now export everything it comes with. Upgrade to either `5.0.0` (Angular 7) or `6.0.0` (Angular 8) to get the changes.
