### ISSUE TITLE
No notifications shown if one notification has been issued before ngOnInit

### ISSUE THREAD

**Issue by nohlnohl7** [dominique-mueller/angular-notifier#127]
I was  debugging a situation where suddenly my notifications where not shown anymore in my Angular app. I have been by accident issuing a notification in my application initializer before the ngOnInit calls. As a result, no notifications where shown at all anymore.

In this case NotifierQueueService isActionInProgress is set to true before the NotifierContainerComponent has subscribed to the queueService.actionStream. As a result, no notifications will be shown due to NotifierQueueService tryToRunNextAction always skipping because of isActionInProgress evaluates to true always.

**Comment by dominique-mueller** [comment]
Fixed by #144.

**Comment by dominique-mueller** [comment]
Release with `6.0.1`. Not that the `6.x` releases of `angular-notifier` require an upgrade to Angular 8.
