### ISSUE TITLE
Angular 8 support 

### ISSUE THREAD

**Issue by AngularTx** [dominique-mueller/angular-notifier#129]
Hi, 

Is there any plan for upgrade to support Angular 8.

**Comment by fliszer** [comment]
Is it still alive repo?

**Comment by elimin8r** [comment]
appears dead

**Comment by WojciechSlyp** [comment]
Aaand how is that coming?

**Comment by dominique-mueller** [comment]
Closed by #139, released as `6.0.0`. Enjoy!
