### ISSUE TITLE
Angular 9

### ISSUE THREAD

**Issue by taokakao** [dominique-mueller/angular-notifier#168]
Pls, upgrade lib to be compliant with Ivy and Angular 9.

**Comment by nkyordy** [comment]
Using angular@9.1.x, and 6.0.1, I've had no issues building using the `--prod` flag.

**Comment by eitanfar** [comment]
First of all, thanks for a great package !

I'd like to also mention that now Angular 10 is out there. Even if the package is fully compatible, it would be nice if you could update the angular dependencies to reflect that, so that using "ng update" wouldn't require the "--force" option.

**Comment by dominique-mueller** [comment]
Released with **[7.0.0](https://github.com/dominique-mueller/angular-notifier/releases/tag/7.0.0)**.
