### ISSUE TITLE
Angular aot compability

### ISSUE THREAD

**Issue by NaLLiFFuNT** [dominique-mueller/angular-notifier#17]
I've compiled my application with aot compilation, i saw the following warning:

activeWarning: Can't resolve all parameters for NotifierConfig in /projectRoot/node_modules/angular-notifier/src/models/notifier-config.model.d.ts: (?). This will become an error in Angular v5.x

**Comment by dominique-mueller** [comment]
Yep, I'm aware of a few issues with the whole NotifierConfig / NotifierOptions part. Also fixed #7 with #8 to resolve some issues with it.

Does it break any functionality, or the build process? If not, I'd fix this when making this library fully compatible with Angular 4.

**Comment by NaLLiFFuNT** [comment]
Right now my app is not ready for aot compilation completely. I can't provide another details now. I'll inform you as soon as i can check it out.
If i don't use aot, everything is okay.

**Comment by dominique-mueller** [comment]
Fix will be published with the next release, which will be version 2.0 due to breaking changes. Still a few things do to until then.

**Comment by dominique-mueller** [comment]
Just published v2 which includes the fix.
