### ISSUE TITLE
pls add support for angular 10

### ISSUE THREAD

**Issue by taokakao** [dominique-mueller/angular-notifier#174]
Pls add support for angular 10. Cant upgrade.

`$ ng update @angular/core @angular/cli

Fetching dependency metadata from registry...
                  Package "angular-notifier" has an incompatible peer dependency to "@angular/core" (requires ">= 8.0.0 < 9.0.0" (extended), would install "10.0.0").
                  Package "angular-notifier" has an incompatible peer dependency to "@angular/common" (requires ">= 8.0.0 < 9.0.0" (extended), would install "10.0.0").

✖ Migration failed: Incompatible peer dependencies found.`

**Comment by MaxSassen** [comment]
Also waiting for an update, is this package still being maintained? 
Because  9 isn't even in yet.

**Comment by fgisslen** [comment]
Also waiting.

**Comment by noririco** [comment]
Please! 🥇

**Comment by taokakao** [comment]
@dominique-mueller save our bundles!!!

**Comment by dominique-mueller** [comment]
Released with **[8.0.0](https://github.com/dominique-mueller/angular-notifier/releases/tag/8.0.0)**.
