### ISSUE TITLE
autoHide does not exist

### ISSUE THREAD

**Issue by phil123456** [dominique-mueller/angular-notifier#193]
dude update your doc please

**Comment by phil123456** [comment]
Argument of type '{ autoHide: number; position: { horizontal: { position: "right"; distance: number; }; vertical: { position: "bottom"; distance: number; gap: number; }; }; }' is not assignable to parameter of type 'NotifierOptions'.
  Object literal may only specify known properties, and 'autoHide' does not exist in type 'NotifierOptions'.

(property) autoHide: number

**Comment by dominique-mueller** [comment]
The docs are actually correct, you forgot the `behaviour` named object that `autoHide` is part of.

Your correct options object would be:

``` diff
  {
+   behaviour: {
      autoHide: number;
+   };
    position: {
      horizontal: {
        position: 'right';
        distance: number;
      }
      vertical: {
        position: 'bottom';
        distance: number;
        gap: number;
      }
    }
  }
```
