### ISSUE TITLE
Notification Close Button not vertically centered

### ISSUE THREAD

**Issue by BenjyTec** [dominique-mueller/angular-notifier#205]
Hey, I'm quite new to Angular and was really happy to find such a sleek package that was providing good-looking notifications. 
I followed the instructions on the ReadMe and got everything to work, except that the close button for the notifications is not vertically centered. See the attached image.
I am using angular-notifier "^9.0.1", together with Angular 11. 
I did the import of the package with "withConfig" in app-module.ts and included the <notifier-container> tag in app.component.html.

If there is anything that I might have done wrong on my side, please kindly let me know. Thanks in advance!

![UncenteredButton](https://user-images.githubusercontent.com/43701845/112827776-14e1d680-908f-11eb-93ae-13b3b3647fee.png)

**Comment by dominique-mueller** [comment]
Just checked the demo app that is included in this repository, styles seem to work just fine. Screenshot:

![image](https://user-images.githubusercontent.com/7271961/112842559-f6390b00-90a1-11eb-9acc-a5de80dfb9c2.png)

Perhaps you have some custom styles in your application that interfer with the notification styles, e.g. on the `<p>` or `<button>` tag?

You could clone and run the demo app on your machine and compare applied styles. Running the demo app means:

- Cloning this repository
- Running `npm install` to install dependencies
- Running `npm run build:library` to build the library
- Running `npm start` to serve the demo app

**Comment by BenjyTec** [comment]
Thanks for the immediate response! I cloned and set up the demo project and indeed, the close button was positioned correctly there. In my projects styles.scss, I only have the one line that is needed for the NotifierService, no other custom styles. Also the related component-specific scss files are empty. I wonder what might be causing this. But for now, I'll just go with disabling the close button, as it actually isn't particularly needed in my use case anyway. Thanks for now!
