### ISSUE TITLE
Not working with angular 12

### ISSUE THREAD

**Issue by mvrueden** [dominique-mueller/angular-notifier#216]
The `angular-notifier` no longer works with angular 12.
Are there any plans on upgrading?
Maybe it is just a simple version bump in the peer dependencies sections, but I am not that familiar with angular.

**Comment by redsd** [comment]
as a temporary fix you could use `npm i angular-notifier --force` since everything seems to be working fine.

**Comment by renxzen** [comment]
how can i tell my package.json to force install this dependency?

**Comment by romekRomek** [comment]
Is there a plan to solve it? Would be great since we use build job where we would like to keep npm install command without additional flag

**Comment by spock123** [comment]
Same with NG13 which is now out. Thanks again

**Comment by Harsh4999** [comment]
> Same with NG13 which is now out. Thanks again

Yeah just faced same issue had to force install it

**Comment by Harsh4999** [comment]
request to make it compatible with NG13

**Comment by kylecannon** [comment]
I have a PR open for it #225. 🤞  @dominique-mueller can review it, merge and publish.

**Comment by dominique-mueller** [comment]
Support for Angular 12 has been released with **[10.0.0](https://github.com/dominique-mueller/angular-notifier/releases/tag/10.0.0)**, and support for Angular 13 (with partial-Icy compilation) with **[11.0.0](https://github.com/dominique-mueller/angular-notifier/releases/tag/11.0.0)**. Enjoy!
