### ISSUE TITLE
Update for Angular 13

### ISSUE THREAD

**Issue by nicolasstevenyates** [dominique-mueller/angular-notifier#224]
Is it possible for you to update angular-notifier for Angular 13?

**Comment by karthi-sekar** [comment]
Any plans to update? If yes, share the timelines

**Comment by kylecannon** [comment]
I have a PR open for it #225. 🤞  @dominique-mueller can review it, merge and publish.

**Comment by karthi-sekar** [comment]
Can we have this PR published. This is blocking our upgrade plans

**Comment by ItzRabbs** [comment]
Seems like the author is done maintaining this. I created builds for angular 12 and 13, and will do so as new versions get released so long as the code doesn't break at all. I don't intend on pushing/merging new features.

Repo: https://github.com/ItzRabbs/angular-notifier/branches
Angular 13 npm package: `npm install @itzrabbs/angular-notifier@11`
Angular 12 npm package: `npm install @itzrabbs/angular-notifier@10`

I personally use the angular 13 compatible build and it looks to be working fine. I haven't tried the angular 12 compatible build besides making sure all the tests run fine.

**Comment by dominique-mueller** [comment]
Support for Angular 12 has been released with **[10.0.0](https://github.com/dominique-mueller/angular-notifier/releases/tag/10.0.0)**, and support for Angular 13 (with partial-Icy compilation) with **[11.0.0](https://github.com/dominique-mueller/angular-notifier/releases/tag/11.0.0)**. Enjoy!
