### ISSUE TITLE
Please update the library peer dependencies to support angular 14

### ISSUE THREAD

**Issue by AshotAleqs** [dominique-mueller/angular-notifier#240]
Hello,

I would like to let you know about the issue connected with Angular 14. 
The Angular project requires the library update. 
Can you please have a look when you get chance.

Thank you for your time and support!

**Comment by bbroereES** [comment]
Can we get some more information about when this is going to be resolved?

**Comment by uberspeck** [comment]
Looks like this has been addressed [in a PR](https://github.com/dominique-mueller/angular-notifier/pull/241). Any chance of getting this merged soon?

**Comment by wn-applover** [comment]
I really ask you to update and close the PR :)

**Comment by bbroereES** [comment]
As we've not seen any activity on the PR in the last two months we might need to consider forking.

**Comment by dominique-mueller** [comment]
Sorry for the delays, I will look into it today

**Comment by dominique-mueller** [comment]
Support for Angular 14 has been released with **[12.0.0](https://github.com/dominique-mueller/angular-notifier/releases/tag/12.0.0)**. Enjoy! :tada:
