### ISSUE TITLE
Angular 15 support

### ISSUE THREAD

**Issue by bbroereES** [dominique-mueller/angular-notifier#250]
Right now angular dependencies are locked at version 14 for @angular/core and @angular/common
I have not tested if it still works with Angular 15.

**Comment by sam-eah** [comment]
Hello, it does work with angular 15, even using inject, I haven't tested it with standalone components though. To install the package with npm, the flag `--legacy-peer-deps` is needed. It would be great if we didn't have to do this.

**Comment by bbroereES** [comment]
Unfortunately, due to other limitations, using `--legacy-peer-deps` is not an option. Woule be great if a small update could be rolled out soon.

**Comment by bbroereES** [comment]
Is there an update to this?

**Comment by evilprince** [comment]
Any update on this ?

**Comment by Chortan** [comment]
Can you update angular-notifier to support Angular 15 ?

**Comment by softsolutionsau** [comment]
@dominique-mueller hey! I'm new to angular-notifier and totally <heart> it! Thank you. I'm also in the same boat with the folks above. I've been able to successfully use notifier with Angular 15, however from a CICD point of view, we're not able to --force or --legacy-peer-deps.

**Comment by enlight3d** [comment]
Any updates on this ?

**Comment by itsdevdom** [comment]
Support for Angular 15 has been released with **[13.0.0](https://github.com/dominique-mueller/angular-notifier/releases/tag/13.0.0)**. Enjoy!
