### ISSUE TITLE
Update the documentation for the component selector

### ISSUE THREAD

**Issue by vajnorcan** [dominique-mueller/angular-notifier#30]
Angular4
Angular-CLI 1.0.3

In your documentation you state that the notifier to be included as
`<x-notifier-component></x-notifier-component>`

But in your src the selector is set as `<notifier-component>`

Please adjust the doco as it is misleading.

**Comment by dominique-mueller** [comment]
Ah yes, you're right, seems I skiped the code example when updating the documentation a few weeks ago. Will correct it as soon as I find the time for it. Thanks!
