### ISSUE TITLE
Not working on route change

### ISSUE THREAD

**Issue by kgrvr** [dominique-mueller/angular-notifier#35]
I am changing route immediately after previewing notification box. 

`
this._notify.notify('success', 'Customer updated!');
this._router.navigate(['/customer']);
`

In this situation above, notification is not working.
Plus after this, any other notification on other pages are also not previewing.

**Comment by dominique-mueller** [comment]
Can you make sure you've put the `notification-container` outside the pages / outside the `router-outlet`, for instance in your app component?

Would also be helpful if you could re-create this issue with a code example, perhaps with a Plunkr :)

**Comment by kgrvr** [comment]
Ya exactly that was issue..needed to put tag in on the root component
Thanks for the reply :)

**Comment by dominique-mueller** [comment]
Great that I was able to help!
