### ISSUE TITLE
Support for custom notification content (template, component)

### ISSUE THREAD

**Issue by JojiePalahang** [dominique-mueller/angular-notifier#37]
Hi Guys,

I wonder if we could do NG selector tags on `snotifyService.html` method.
like this one.

 _this.snotifyService.html(`
    <div class="snotifyToast__title" *ngIf="toast.title">
        <ng-notifiersomethinghere> </ng-notifiersomethinghere>
      </div>
    </div>`
    , {
        timeout: this.timeout,
        showProgressBar: this.progressBar,
        closeOnClick: this.closeClick,
        pauseOnHover: this.pauseHover,
      });_

for better and cleaner code and component reusability.

Just an inquiry

Thanks, 
Jojie Palahang

**Comment by dominique-mueller** [comment]
Love the idea of passing in more than just a simple text. I could imagine to extend the API allowing both template refs and component types to be passed in as the content. Already implemented someting like this for a modal component some place else.

**Comment by JojiePalahang** [comment]
Great (y)

**Comment by dominique-mueller** [comment]
The feature of using `ng-template` as notification content has been released with `4.1.0`. Closed by https://github.com/dominique-mueller/angular-notifier/pull/95.
