### ISSUE TITLE
angular 5 support?

### ISSUE THREAD

**Issue by rwpino** [dominique-mueller/angular-notifier#41]
Hello: 
I m having this warning on my angular 5 project
`angular-notifier@2.0.0 requires a peer of @angular/common@>= 4.0.0 < 5.0.0 but none is installed. You must install peer dependencies yourself.`
this start to happen to me after my migration to angular 5
any plans to add angular 5 support ?
greetings

**Comment by dominique-mueller** [comment]
Actually in progress right now (#38, #39, #49) - will make a new release soon :)

**Comment by dominique-mueller** [comment]
Fresh out, angular-notifier `3.0.0` with Angular 5 support!

Changelog: https://github.com/dominique-mueller/angular-notifier/blob/develop/CHANGELOG.md

**Comment by rwpino** [comment]
thanks!
