### ISSUE TITLE
Angular 6 support

### ISSUE THREAD

**Issue by NaLLiFFuNT** [dominique-mueller/angular-notifier#82]
Hi, when are you going to implement Angular 6 compatibility?

**Comment by dominique-mueller** [comment]
PR for the update is open: https://github.com/dominique-mueller/angular-notifier/pull/80. Need to finish some updates on the angular package builder, hopefully next week we can make this library Angular 6 compatible.

**Comment by witek1902** [comment]
Hello Dominique, how it's going?
I am waiting impatiently for Angular 6 support ;)

**Comment by dominique-mueller** [comment]
Here we finally go, just release `4.0.0` with support for Angular 6. Have fun!

**Comment by witek1902** [comment]
Thank you!
