### ISSUE TITLE
Feature proposal: Allow to pass in a templateRef

### ISSUE THREAD

**Issue by juristr** [dominique-mueller/angular-notifier#94]
Hi,

I'm looking at your implementation of notifications in Angular and really like your clean code. I was thinking about extending it, allowing for some more heavy customization. In my case, I cannot really use your material style as it doesn't go well together with the Clarity design system style which is used by the app I'm working on. I would need something that looks more like this:

![image](https://user-images.githubusercontent.com/542458/43636209-b3528802-9711-11e8-8af6-500bf89c9585.png)

Still I'd like to make use of your animation, stacking behavior etc. The idea would be to allow to also pass a template reference to the `NotifierService`, something like

```
export class SomeComponent {
   ...
   @ViewChild('notificationTmpl) notificationTmpl;

   showNotification() {
      this.notifier.show({
        message: msg.message,
        type: msg.messageType,
        template: this.notificationTmpl
      });
   }
```

Inside the `notifier-notification.component`

https://github.com/dominique-mueller/angular-notifier/blob/1e26507667a7f0f4013d9d6ade8d75186b2a5b50/src/lib/src/components/notifier-notification.component.html#L1-L7

...I'd then check whether that template has been defined. If it has, then instantiate it there, passing to it the details about the message etc, and if not, just fallback to the current behavior.

What do you think about this? It would really allow to heavily customize the notifications, allowing for icons and whatever the user wants, still taking benefit from the whole logic you've already implemented 😄. I can provide a PR for this

**Comment by juristr** [comment]
In case, I have a working demo ready.

**Comment by juristr** [comment]
Btw, do you also get this error while building the package?

![image](https://user-images.githubusercontent.com/542458/43637593-e24f17fc-9715-11e8-979f-b33ea9a28f23.png)

Problem is basically jest and jest-preset both defining the same types 🤔 
![image](https://user-images.githubusercontent.com/542458/43637748-6aa9ae1e-9716-11e8-8d6c-5c99838ff0bd.png)

**Comment by dominique-mueller** [comment]
I like the idea, happy to accept a PR :)

**Comment by dominique-mueller** [comment]
Related to https://github.com/dominique-mueller/angular-notifier/issues/37.

**Comment by juristr** [comment]
👍 Alright, PR coming soon

**Comment by juristr** [comment]
@dominique-mueller I submitted PR #95. If you could give it a look & in case merge + publish it, that'd be awesome. So I can straight use it in my app and continue 😃. thx

**Comment by dominique-mueller** [comment]
Closed by https://github.com/dominique-mueller/angular-notifier/pull/95.
