### ISSUE TITLE
add html method

### ISSUE THREAD

**Issue by kyusupov33** [dominique-mueller/angular-notifier#96]
![image](https://user-images.githubusercontent.com/29026701/43648549-6136a7ce-9743-11e8-8097-5bcff4f176dc.png)
![image](https://user-images.githubusercontent.com/29026701/43648596-8764a13a-9743-11e8-9c4e-05ba8fdd0a07.png)

**Comment by dominique-mueller** [comment]
Just released `4.1.0` which comes with the feature of using custom a ng-template as a notification content. 
Thus, closed by https://github.com/dominique-mueller/angular-notifier/pull/95.
